<?php
use yii\helpers\Html;
use yii\helpers\Url;
?>
<div class="header">
    <h1>CONTRIBUTION DETAILS</h1>
    <p><strong>Generated on:</strong> <?= date('Y-m-d H:i:s') ?></p>
    <p><strong>Reference:</strong> <?= Html::encode($model->id) ?></p>
</div>

<h3>Member Information</h3>
<table class="table">
    <tr>
        <th style="width: 40%;">Field</th>
        <th style="width: 60%;">Details</th>
    </tr>
    <tr>
        <td><strong>Member Number</strong></td>
        <td><?= Html::encode($model->member_number) ?></td>
    </tr>
    <tr>
        <td><strong>Transaction ID</strong></td>
        <td><?= Html::encode($model->transaction_id) ?></td>
    </tr>
</table>

<h3>Contribution Details</h3>
<table class="table">
    <tr>
        <th style="width: 40%;">Field</th>
        <th style="width: 60%;">Details</th>
    </tr>
    <tr>
        <td><strong>Contribution Date</strong></td>
        <td><?= Html::encode($model->date_time) ?></td>
    </tr>
    <tr>
        <td><strong>Contribution Period</strong></td>
        <td><?= Html::encode($model->contributing_period) ?></td>
    </tr>
    <tr>
        <td><strong>Month/Year</strong></td>
        <td><?= Html::encode($model->cont_month) ?> / <?= Html::encode($model->cont_year) ?></td>
    </tr>
    <tr>
        <td><strong>Salary</strong></td>
        <td><?= Yii::$app->formatter->asCurrency($model->salary) ?></td>
    </tr>
    <tr>
        <td><strong>Contribution Amount</strong></td>
        <td><span class="bold"><?= Yii::$app->formatter->asCurrency($model->amount) ?></span></td>
    </tr>
</table>

<h3>System Information</h3>
<table class="table">
    <tr>
        <th style="width: 40%;">Field</th>
        <th style="width: 60%;">Details</th>
    </tr>
    <tr>
        <td><strong>Record ID</strong></td>
        <td><?= Html::encode($model->id) ?></td>
    </tr>
    <tr>
        <td><strong>Last Updated</strong></td>
        <td><?= Html::encode($model->latest_updated) ?></td>
    </tr>
</table>

<div class="footer">
    <p><strong>Document generated from:</strong> <?= Html::encode(Yii::$app->name) ?></p>
    <p><strong>System URL:</strong> <?= Url::home(true) ?></p>
    <p><strong>Generated by:</strong> <?= Yii::$app->user->identity->username ?> | <strong>Date:</strong> <?= date('Y-m-d H:i:s') ?></p>
    <p class="text-center">--- END OF DOCUMENT ---</p>
</div>